# Generated by Django 4.0 on 2021-12-29 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Original',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_image', models.ImageField(upload_to='original')),
                ('out_image', models.ImageField(upload_to='output')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('pass1', models.CharField(max_length=100)),
                ('pass2', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('India', 'India'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Egypt', 'Egypt')], default='Indai', max_length=200)),
                ('type_standard', models.BooleanField(default=False)),
                ('type_pro', models.BooleanField(default=False)),
                ('type_advanced', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.original')),
            ],
        ),
        migrations.AddField(
            model_name='original',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register'),
        ),
    ]
