# Generated by Django 4.0 on 2022-01-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserPlan',
        ),
    ]
