# Generated by Django 4.0 on 2022-01-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_delete_userplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'User Registration', 'verbose_name_plural': 'User Registration'},
        ),
    ]
