# Generated by Django 4.0 on 2022-01-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_register_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'inquiry', 'verbose_name_plural': 'inquiries'},
        ),
        migrations.AlterModelOptions(
            name='original',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'User Registration', 'verbose_name_plural': 'User Registrations'},
        ),
    ]
