# Generated by Django 4.0 on 2022-01-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_contact_options_alter_original_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='register',
            name='country',
            field=models.CharField(max_length=200),
        ),
    ]
